name: Monthly Automated Newsletter Script

on:
  schedule:
    - cron: '* 10 1 * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run newsletter script
        run: python $GITHUB_WORKSPACE/src/generate_newsletter.py
        env:
          SCOPUS_API_KEY: ${{ secrets.SCOPUS_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Send newsletter email
        run: python $GITHUB_WORKSPACE/src/send_newsletter.py
        env:
          GOOGLE_APP_PASSWORD: ${{ secrets.GOOGLE_APP_PASSWORD }}

      - name: Authenticate with DagsHub S3
        run: |
          dvc remote modify origin endpointurl https://dagshub.com/ayonitemiferanmi/Automated_Newsletter.s3
          dvc remote modify origin --local access_key_id ${{ secrets.DAGSHUB_S3_ACCESS_KEY }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DAGSHUB_S3_SECRET_KEY }}

      - name: Track Data with DVC
        run: |
          dvc add data/Research_Articles_Datasets.csv outputs/Newsletter-Latest-Edition.txt
          git add data/Research_Articles_Datasets.csv.dvc outputs/Newsletter-Latest-Edition.txt.dvc .gitignore
          git commit -m "Auto-update versioned data for the month" || echo "No changes to commit"
      
      - name: Push changes to Github
        run: git push origin main || echo "No changes to push"

      - name: Push data to Dagshub
        run: dvc push || echo "No new data changes to push"